#!/bin/sh

FILES="314.png
      314_thumb.png
      datamapper.png
      datamapper_thumb.png
      activerecord.png
      activerecord_thumb.png
      sequel.png
      sequel_thumb.png
      datamapper_noshadow.png
      datamapper_noshadow_thumb.png
      editor.png
      editor_thumb.png
      file.png
      file_thumb.png
      index.css
      index.html
      ubuntu-new-tk.html
      "

scp $FILES mooffie@rubyforge.org:/var/www/gforge-projects/drx/
